version: '3.8'

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
     - './server:/usr/src'
    ports:
     - "8000:8000"
    tty: true
    stdin_open: true
    depends_on:
     - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
     - './client/mysite:/usr/src'
    ports:
     - "8080:8080"
    tty: true
    stdin_open: true
    depends_on:
     - server
    environment:
     - NODE_ENV=development
  
  db:
   image: mysql:5.7
   container_name: mysql
   environment:
     MYSQL_DATABASE: "fd_collection"
     MYSQL_USER: fd
     MYSQL_PASSWORD: fdfast
     MYSQL_ROOT_PASSWORD: fdfastrootstrong
   volumes:
     - ./database:/var/lib/mysql
     - ./my.cnf:/etc/mysql/conf.d/my.cnf
   ports:
     - 3306:3306