# Generated by Django 3.2.12 on 2023-05-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_user_id', models.CharField(max_length=10)),
                ('twitch_reward_id', models.CharField(max_length=256)),
                ('get_date', models.DateTimeField()),
                ('valid_flag', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'collection',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_reward_id', models.CharField(max_length=256)),
                ('reward_title', models.CharField(max_length=256)),
                ('reward_parent_flag', models.BooleanField()),
                ('reward_parent_id', models.IntegerField(null=True)),
                ('reward_content', models.CharField(max_length=256, null=True)),
                ('reward_img_path', models.CharField(max_length=256, null=True)),
                ('reward_audio_path', models.CharField(max_length=256, null=True)),
                ('valid_flag', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'reward',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_user_id', models.CharField(max_length=10)),
                ('user_login', models.CharField(max_length=256)),
                ('user_name', models.CharField(max_length=256, null=True)),
                ('valid_flag', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
